Application expanded with unit tests
NexusMutual/cover-router pull request #23
Opened 2023-03-16 08:36 UTC by MilGard91

Unit tests for cover-router:
- quoteEngine
- capacityEngine

2023-03-16 10:02 UTC, shark0der requested changes
Change mock hex numbers to decimal please

2023-03-16 10:06 UTC, shark0der commented on test/unit/capacityEngine.js
> +      expect(amount.toString()).not.to.be.equal('0');
Is this too generic?

2023-03-29 13:34 UTC, roxdanila approved these changes

2023-04-04 13:42 UTC, roxdanila approved these changes

2023-04-04 13:42 UTC, merged