Change the way that max premium is calculated
NexusMutual/cover-router pull request #81
Opened 2024-04-04 07:37 UTC by MilGard91

## Context

Issue: #79 

## Changes proposed in this pull request

- Add a function that will calculate premium for next 4 tranches and return max premium of the pool

## Test plan

Please describe the tests cases that you ran to verify your changes. Add further instructions on 
how to run them if needed (i.e. migration / deployment scripts, env vars, etc).

## Checklist

- [ ] Rebased the base branch
- [ ] Attached corresponding Github issue
- [ ] Prefixed the name with the type of change (i.e. feat, chore, test)
- [ ] Performed a self-review of my own code
- [ ] Followed the style guidelines of this project
- [ ] Made corresponding changes to the documentation
- [ ] Didn't generate new warnings
- [ ] Didn't generate failures on existing tests
- [ ] Added tests that prove my fix is effective or that my feature works

## Review

When reviewing a PR, please indicate intention in comments using the following emojis:
* :cake: = Nice to have but not essential.
* :bulb: = Suggestion or a comment based on personal opinion
* :hammer: = I believe this should be changed.
* :thinking: = I don’t understand something, do you mind giving me more context?
* :rocket: = Feedback

2024-04-05 13:16 UTC, roxdanila commented on src/lib/capacityEngine.js
> +        const poolPremium = calculateMaxPremium(product, pool, basePrice, time);
fixed price products don't have surge, so it's fine to not enter to for loop and return here, as before

2024-04-05 13:17 UTC, roxdanila commented on src/lib/capacityEngine.js
> +    maxPremium = bnMax(poolPremium, maxPremium);
you're adding up max premiums on different pools that could be on different periods. you have to first calculate maxes on all periods, sum them up on all pools, and only then find the absolut max

2024-04-05 13:17 UTC, roxdanila requested changes
see comments

2024-04-05 15:36 UTC, MilGard91 commented
Fixed the max premium calculation by extracting the productData reducer and using it to calculate the product data for next five tranches (4 - tranches 364 days, and max premium is 365 so just in case added one more iteration). Finding the max premium while iterating and also the capacity data for the requested period. All of this is skipped if the product has fixed price and calculating everything just for a requested period.

2024-04-08 11:49 UTC, roxdanila approved these changes

2024-04-08 11:49 UTC, merged