fix: remove old data
NexusMutual/cover-router pull request #95
Opened 2024-06-10 11:25 UTC by MilGard91

## Context

Issue: #91 

## Changes proposed in this pull request

Add an action to remove old data from the store so it's doesn't affect the result in the capacity and quote engines

## Test plan

N/A

## Checklist

- [x] Rebased the base branch
- [x] Attached corresponding Github issue
- [x] Prefixed the name with the type of change (i.e. feat, chore, test)
- [x] Performed a self-review of my own code
- [x] Followed the style guidelines of this project
- [ ] Made corresponding changes to the documentation
- [x] Didn't generate new warnings
- [x] Didn't generate failures on existing tests
- [ ] Added tests that prove my fix is effective or that my feature works

## Review

When reviewing a PR, please indicate intention in comments using the following emojis:
* :cake: = Nice to have but not essential.
* :bulb: = Suggestion or a comment based on personal opinion
* :hammer: = I believe this should be changed.
* :thinking: = I don’t understand something, do you mind giving me more context?
* :rocket: = Feedback

2024-06-11 12:19 UTC, rackstar commented on src/store/reducer.js
> +    const { productId, poolIds } = payload;
or we move the logic for `poolIdsToRemove = ...` out of reducer and into the synchornizer so `poolIds` is actually the ids that needs to be removed

2024-06-11 16:12 UTC, roxdanila commented
Can you also fill in the Context section explaining what the bug is?

2024-06-11 16:12 UTC, roxdanila requested changes
See comments

2024-06-13 15:53 UTC, roxdanila approved these changes

2024-06-13 15:54 UTC, merged